export const DummyJobsData = [
  {
    cityCode: "CICO101000",
    cityName: "서울",
    comLogo:
      "https://dditjob-image-bucket.s3.ap-northeast-2.amazonaws.com/2025-07-29/dummy_logo_1.png",
    comName: "카카오",
    districtCode: "101020",
    districtName: "서초구",
    education: {
      educationCodeDetailNo: null,
      recruitmentEducationCode: "REED000070",
      recruitmentEducationCodeName: "학력무관",
    },
    jobCode: "2201",
    jobName: "마케팅",
    positionList: [],
    preferential: null,
    recContent:
      "<p>카카오에서 마케팅 인재를 모집합니다. <br>신입 및 경력 모두 지원 가능합니다.</p>",
    recruitFinishYn: "N",
    recruitmentFinishDate: "2025-08-31 00:00:00",
    recruitmentImg:
      "https://dditjob-image-bucket.s3.ap-northeast-2.amazonaws.com/2025-07-30/dummy_image_1.png",
    recruitmentNo: "RECR000100",
    recruitmentSalary: "5000",
    recruitmentStartDate: "2025-08-01 10:00:00",
    recruitmentTitle: "[카카오] 마케팅 인턴/정규직 모집",
    scrabCnt: 0,
    skillList: [
      { recruitSkillCode: "RESK000148", recruitSkillName: "PowerPoint" },
      { recruitSkillCode: "RESK000147", recruitSkillName: "Excel" },
    ],
    userId: "kakao",
    viewCnt: 3,
    yearCode: "YEXP-Y0",
    yearCodeName: "신입",
  },
  {
    cityCode: "CICO101000",
    cityName: "서울",
    comLogo:
      "https://dditjob-image-bucket.s3.ap-northeast-2.amazonaws.com/2025-07-29/dummy_logo_2.png",
    comName: "네이버",
    districtCode: "101030",
    districtName: "종로구",
    education: {
      educationCodeDetailNo: null,
      recruitmentEducationCode: "REED000070",
      recruitmentEducationCodeName: "학력무관",
    },
    jobCode: "2202",
    jobName: "디자인",
    positionList: [],
    preferential: null,
    recContent: "<p>창의적인 디자이너를 찾습니다. 포트폴리오 필수 제출.</p>",
    recruitFinishYn: "N",
    recruitmentFinishDate: "2025-09-15 00:00:00",
    recruitmentImg:
      "https://dditjob-image-bucket.s3.ap-northeast-2.amazonaws.com/2025-07-30/dummy_image_2.png",
    recruitmentNo: "RECR000101",
    recruitmentSalary: "5500",
    recruitmentStartDate: "2025-08-01 10:00:00",
    recruitmentTitle: "[네이버] UI/UX 디자이너 채용",
    scrabCnt: 0,
    skillList: [
      { recruitSkillCode: "RESK000151", recruitSkillName: "Photoshop" },
      { recruitSkillCode: "RESK000152", recruitSkillName: "Illustrator" },
    ],
    userId: "naver",
    viewCnt: 5,
    yearCode: "YEXP-Y2",
    yearCodeName: "2년",
  },
];
